// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"Ethers","status":true,"description":"Connect your wallet with RM MZ!","parameters":{"DEV_PRIVATE_KEY":"0x513e5af74d415831f91e4de1e0f32826a4f67591158245c15f2697a59da27dbb"}}
];
